name:                BadmintonRanking
version:             0.1.0.0
github:              "githubuser/BadmintonRanking"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/BadmintonRanking#readme>

dependencies:
- base >= 4.7 && < 5
- webdriver-w3c
- text
- data-default
- hasbolt
- containers
- mtl
- http-client
- servant
- servant-server
- transformers
- aeson
- wai
- warp
- swagger2
- servant-swagger
- servant-swagger-ui

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-type-defaults
- -Wno-missing-signatures
- -Wno-orphans

library:
  source-dirs: 
    - src

executables:
  BadmintonRanking-exe:
    main:                Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BadmintonRanking

tests:
  BadmintonRanking-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-type-defaults
    dependencies:
    - BadmintonRanking
    - hspec
    - text
